### PR TITLE
#106 Implement Login and Registration E2E testing

### PR DESCRIPTION
**Pull request by laurent-lao**
All checks should be green.

I added a bunch of `name=""` decorators to react components that did not have them.
This allowed me to quickly use them via Cypress.

Example:
`<TextField name="email" ...... />`
`<Button name="next-button" ...... > Next </Button>`

In cypress
`cy.get('input[name="email"]').type("lao.laurent@gmail.com")`
`cy.get('button[name="next-button"]').click()`

### CODE REVIEW

**Comment by zaad97** [comment]
All checks are indeed green

**Review by zaad97 — APPROVED** [review]
All checks are indeed green

**Review by zaad97 — APPROVED** [review]
After the mini-update you did, all 3 checks are green

**Comment by laurent-lao** [comment]
Closes #108

**Pull request merged**
