### PR TITLE
Issue 4 backend refactor

### PR DESCRIPTION
**Pull request by laurent-lao**
This PR is progress on #4 and adds the following changes
* Refactor index.js into separate components
* Hides secrets using dotenv
* Tests our API with Jest + Supertest

Accept this PR after:
* Trying to run the backend server without `.env`: backend won't be connected to db
* Create a `.env` file in the root of the `backend` folder with valid credentials: backend should now work
* Perform `npm test` on backend and all tests should pass

### CODE REVIEW

**Comment by laurent-lao** [comment]
Prepares the ground for authentication related to #2 #3

**Comment by laurent-lao** [comment]
This PR now also includes linters for both backend and frontend and is setup with circleci.

**Comment by laurent-lao** [comment]
#4 Continuous Integration now set with Circleci. Still need to deploy automatically

**Comment by hubjongit** [comment]
Although this PR encompasses changes made for the CI/CD and CircleCI represented by Issue #4, these changes were made on a separate and incorrect branch. Please see comments in #72 for explanation and reason for no branch representing these changes existing.

**Pull request merged**
